from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import  os
dir=os.path.dirname(__file__)
path=dir+"/chromedriver.exe"
driver=webdriver.Chrome(path)
driver.get("http://127.0.0.1/forum.php")
name=driver.find_element_by_name("username")
name.send_keys("admin")
pwd=driver.find_element_by_name("password")
pwd.send_keys("root")
button=driver.find_element_by_css_selector("button em")
button.click()
driver.switch_to.window(driver.current_window_handle)
time.sleep(7)



moren=driver.find_element_by_css_selector(".fl_icn a")
moren.click()
driver.switch_to.window(driver.current_window_handle)
duigou=driver.find_element_by_name('moderate[]')
duigou.click()
shanchu=driver.find_element_by_link_text('删除')
shanchu.click()
dianji=driver.find_element_by_name('modsubmit')
dianji.click()
driver.find_element_by_link_text('管理中心').click()
# driver.find_element_by_name('admin_password').send_keys('root')
# driver.find_element_by_name("submit").click()
time.sleep(5)
driver.switch_to.window(driver.window_handles[1])
driver.find_element_by_link_text('论坛').click()
driver.switch_to.frame(driver.find_element_by_tag_name('iframe'))
time.sleep(1)
driver.find_element_by_link_text('添加新版块').click()
time.sleep(2)
driver.find_element_by_name("newforum[1][]").clear()
time.sleep(2)
driver.find_element_by_name("newforum[1][]").send_keys('模块模块')
driver.find_element_by_id('submit_editsubmit').click()
driver.switch_to.window(driver.current_window_handle)
driver.find_element_by_link_text('退出').click()
time.sleep(2)
driver.switch_to.window(driver.current_window_handle)
driver.find_element_by_link_text('退出').click()
# driver.switch_to.window(driver.current_window_handle)
# driver.find_element_by_id('ls_username').send_keys("root")
# driver.find_element_by_id('ls_password').send_keys("root11")
time.sleep(5)
name.send_keys("root")
pwd.send_keys("root11")
button.click()
driver.switch_to.window(driver.current_window_handle)
time.sleep(5)
driver.find_element_by_link_text("aaaa").click()
#driver.find_element_by_css_selector('.fl_row td:nth-child(2)').click()
time.sleep(5)
driver.switch_to.window(driver.current_window_handle)
fatie=driver.find_element_by_id("newspecial")
fatie.click()
driver.switch_to.window(driver.current_window_handle)
title=driver.find_element_by_name("subject")
title.send_keys("标题")
driver.switch_to.frame(driver.find_element_by_tag_name("iframe"))
neirong=driver.find_element_by_tag_name("body")
neirong.send_keys("%%%%%%%%%%%%%%adjfjka")
time.sleep(4)
driver.switch_to.window(driver.current_window_handle)
fabiao=driver.find_element_by_id("postsubmit")
fabiao.click()
driver.switch_to.window(driver.window_handles[0])
time.sleep(5)
huifu=driver.find_element_by_id("post_reply")
huifu.click()
driver.switch_to.window(driver.current_window_handle)
hfnr=driver.find_element_by_name("message")
hfnr.send_keys("huifufhuifhuif")
hffb=driver.find_element_by_id("postsubmit")
hffb.click()
tuichu=driver.find_element_by_link_text("退出")
tuichu.click()